# Note: there are many handy hints in comments in this example -- remove them when you've finalized your recipe

# Jinja variables help maintain the recipe as you'll update the version only here.
# Using the name variable with the URL in line 14 is convenient
# when copying and pasting from another recipe, but not really needed.
{% set name = "seedbank" %}
{% set version = "0.1.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: a859761f1a7545c8cf24a6c19af80c25b90294723a9a20f6c220cac2b6084586

build:
  noarch: python
  number: 1
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python {{ python_min }}
    - pip
    - flit-core >=2
  run:
    - python >={{ python_min }}
    - numpy >=1.17
    - anyconfig >=0.12

test:
  # Some packages might need a `test/commands` key to check CLI.
  # List all the packages/modules that `run_test.py` imports.
  imports:
    - seedbank
  requires:
    - pip
    - python {{ python_min }}
  commands:
    - pip check

about:
  home: https://seedbank.lenskit.org
  license: MIT
  license_family: MIT
  license_file: LICENSE.md
  summary: Unified API for seeding random number generators.
  description: |
    seedbank is a unified API for seeding a wide range of random number generators
    with a single seed call, and managing more sophisticated seeding needs through
    its support for NumPy generators and derived seeds.
  doc_url: https://seedbank.lenskit.org
  dev_url: https://github.com/lenskit/seedbank

extra:
  recipe-maintainers:
    - mdekstrand
